client/package-lock.json
client/package.json
client/src/components/Footer.jsx
client/src/components/HomePage/Footer.jsx
client/src/components/HomePage/Hero.jsx
client/src/components/HomePage/MiddleSection.jsx
client/src/components/HomePage/SearchBar.jsx
client/src/components/HomePage/Team.jsx
client/src/components/Navbar.jsx
client/src/page/HomePage.jsx

I already tested the page and looks good.

landing page 1st draft

---

.eslintrc.js
bin/www
db/models/index.js
psql-setup-script.js
routes/api/index.js
routes/api/mentee.js
routes/api/mentor.js
routes/index.js

Mentee and Mentor Get routes

---

frontend/src/components/Home/Hero.js

Style: Link logos #22
Navbar:
Footer:

{BUG] Connected logos

---

frontend/src/assets/People.json
frontend/src/components/Home/Footer.js
frontend/src/components/Home/Team.js

Updated the team section 🥳
Will add more info later. @yi-lin-1234 👍🏼

[STYLE] Updated team section #30

---

frontend/src/components/Signup/SignupForm.js
frontend/src/page/MentorList.js

The Mentor list is now renderable on the frontend

Mentor list rendering issue

---

frontend/src/components/Login/LoginForm.js
frontend/src/components/MentorDetail/DetailCard.js
frontend/src/page/MentorDetail.js
frontend/src/page/MentorList.js
frontend/src/store/index.js
frontend/src/store/mentee.js
frontend/src/store/mentor.js
server/routes/api/mentor.js

Add demo mentee and demo mentor users to the login page

added demo mentor and demo mentee components

---

frontend/src/App.js
frontend/src/components/MentorCard/MentorCard.js
frontend/src/page/MenteeDetail.js
frontend/src/store/mentee.js
frontend/src/store/mentor.js
server/bin/www
server/db/migrations/20230509180023-create-mentor.js
server/db/migrations/20230509180244-create-mentee.js
server/db/models/mentee.js
server/db/models/mentor.js
server/db/seeders/20230509213837-demo-mentor.js
server/db/seeders/20230509213851-demo-mentee.js
server/routes/api/mentee.js
server/routes/api/mentor.js

added Mentee and Mentor edit backend/frontend functionality, added phone & country codes to Mentee and Mentor models, the addition of the mentee user information for the Menteedetail component.

added Mentee and Mentor edit backend/frontend functionality

---

frontend/src/components/Signup/SignupMentor.js

**Task Description**
- Update the Signup Mentor page
**Technical Considerations**
-None
Additional Considerations
- Refers to #42 
Screenshot After:

[STYLE] Update Signup Mentor page

---

frontend/src/components/Home/Hero.js

[STYLE] Updated Nav buttons

---

frontend/src/components/Home/Hero.js

Reverts chingu-voyages/v44-tier3-team-41#48

Revert "[STYLE] Updated Nav buttons"

---

frontend/src/components/Home/Hero.js

Reverts chingu-voyages/v44-tier3-team-41#52

Revert "Revert "[STYLE] Updated Nav buttons""

---

frontend/src/assets/People.json
frontend/src/components/Home/Hero.js

[STYLE] Made Navbar sticky

---

frontend/src/components/Home/Hero.js
frontend/src/components/Login/LoginForm.js
frontend/src/components/Signup/SignupMentee.js
frontend/src/components/Signup/SignupMentor.js
frontend/tailwind.config.js

- Updated Login & Sign up pages
Before:
After:

[STYLE] Updated Login & Sign up pages

---

frontend/src/components/Profile/ProfileMentor.js
frontend/src/page/DashBoardSideBar.js

Before:
After:
Still in progress...

[STYLE] Update Profile page

---

frontend/src/components/Login/LoginForm.js

[STYLE] Fix Login style

---

frontend/src/components/Profile/ProfileMentee.js
frontend/src/components/Profile/ProfileMentor.js

- Updated Mentee profile
Before:
After:

[STYLE] Update Mentee profile

---

frontend/public/index.html
frontend/src/components/Home/Hero.js

[MOBILE] Hero Mobile update

---

frontend/public/index.html
frontend/src/components/Home/Hero.js

Revert "[MOBILE] Hero Mobile update"

---

frontend/src/assets/People.json
frontend/src/components/Login/LoginForm.js
frontend/src/page/DashBoardSideBar.js

The sign out button will now remove the current session user, and assign a 'null' user to the Redux session store. The Demo login buttons are now also functional.

linked the sign out button to the Redux store logoutThunk function

---

frontend/src/components/MentorCard/MentorCard.js
frontend/src/page/MentorList.js

[STYLE] Mentorlist update

---

frontend/src/components/MenteeCard/MenteeCard.js
frontend/src/components/MentorCard/MentorCard.js
frontend/src/page/MenteeList.js
frontend/src/page/MentorList.js

- Made more updates to Mentor/Mentee Cards
Mentor After:
Mentee After:

[STYLE] Card updates

---

README.md
frontend/src/components/Chart/BarChart.js
frontend/src/components/Profile/ProfileMentee.js
frontend/src/page/JobBoard.js
frontend/src/page/MessageBoard.js
frontend/src/page/Report.js
frontend/src/page/Search.js

- Made updates to all Dashboard
Report After:
Job After:
Search After:

[STYLE] Updates rest of dashboard

---

frontend/src/components/Home/Hero.js
frontend/src/components/Profile/ProfileMentee.js
frontend/src/page/DashBoardSideBar.js
frontend/src/page/JobBoard.js
frontend/src/page/MenteeList.js
frontend/src/page/MentorList.js
frontend/src/page/MessageBoard.js
frontend/src/page/Report.js
frontend/src/page/Search.js

[STYLE] Dashboard color updates

---

frontend/src/components/Home/Footer.js
frontend/src/components/Home/Hero.js
frontend/src/components/Home/MiddleSection.js
frontend/src/components/Home/Team.js
frontend/src/components/Login/LoginForm.js
frontend/src/components/Signup/SignupMentee.js
frontend/src/components/Signup/SignupMentor.js
frontend/src/page/MenteeList.js
frontend/src/page/MentorList.js
frontend/src/page/MessageBoard.js
frontend/src/page/Search.js

[STYLE] Still busy

---

frontend/src/App.js
frontend/src/components/Home/Hero.js
frontend/src/components/Login/LoginForm.js
frontend/src/page/DashBoardSideBar.js
frontend/src/page/JobBoard.js
frontend/src/page/SearchMentees.js
frontend/src/page/SearchMentors.js

1. The 'All Mentors' and 'All Mentees' tabs have been removed. This change aims to streamline the user interface and improve navigation.
2. In their place, two new tabs - 'Search Mentors' and 'Search Mentees' - have been added to facilitate a more user-centric experience.
3. While testing, I've noticed that the 'Search Mentors' tab functions as expected, but the 'Search Mentees' tab does not. I've attempted to debug, but it appears there may be an issue with how the frontend and backend are linked in this particular instance.

update the dashboard sidebar

---

frontend/src/components/Home/Hero.js
frontend/src/page/AiChat.js
frontend/src/page/DashBoardSideBar.js
frontend/src/page/VideoCall.js

Update ai chat page

---

frontend/src/components/Home/Hero.js
frontend/src/page/DashBoardSideBar.js
frontend/src/page/VideoCall.js

[STYLE] Updated Video Call Page

---

frontend/src/components/Profile/ProfileMentor.js
frontend/src/page/MenteeDetail.js
frontend/src/page/MentorDetail.js

[STYLE] Mentor/Mentee detail page updates

---

frontend/src/components/Home/Hero.js
frontend/src/components/Home/Scroll.js
frontend/src/page/Home.js
frontend/tailwind.config.js
package-lock.json
package.json

[STYLE] Added logo scroll

---

frontend/src/components/Login/LoginForm.js
frontend/src/components/Signup/SignupMentee.js
frontend/src/components/Signup/SignupMentor.js
frontend/src/page/AboutUs.js
frontend/src/page/DashBoardSideBar.js

[STYLE] About page update

---

frontend/src/components/Home/Hero.js
frontend/src/page/AiChat.js
frontend/src/page/Report.js

[STYLE] Ai Updates

---

frontend/src/page/AboutUs.js

Will add the form later.
Before:
After:

[STYLE] Removed Contact form

---

frontend/src/page/AboutUs.js

[STYLE] Contact update

---

frontend/src/assets/People.json
frontend/src/page/AboutUs.js

[STYLE] About update

---

frontend/src/assets/Tech.json
frontend/src/components/Home/Scroll.js
frontend/tailwind.config.js

[STYLE] Scroll update

---

README.md

[BUG] Cleaner readme
